// Seed list imported from "300 Tunes - Sax.xlsx".
// keys: common concert keys (first = most common). Sourced from the iReal Pro jazz
// collection via github.com/mikeoliphant/JazzStandards, with a few hand edits for
// tunes regularly called in more than one key.
// level: 0 = don't know, 1 = familiar, 2 = proficient, 3 = mastered (omitted = not rated)
export const SEED_TUNES = [
  {"name": "All The Things You Are", "keys": ["Ab"], "style": "Standard", "priority": 1, "level": 1},
  {"name": "Anthropology", "keys": ["Bb"], "style": "Rhythm Changes", "priority": 1},
  {"name": "Autumn Leaves", "keys": ["Gm", "Em"], "style": "Standard", "priority": 1, "level": 2, "notes": "From spreadsheet: B (Gm) / C (Em)"},
  {"name": "Billie’s Bounce", "keys": ["F"], "style": "Blues", "priority": 1},
  {"name": "Blue Bossa", "keys": ["Cm"], "style": "Latin", "priority": 1, "level": 1},
  {"name": "Body and Soul", "keys": ["Db"], "style": "Ballad", "priority": 1},
  {"name": "Cherokee", "keys": ["Bb"], "style": "Standard", "priority": 1},
  {"name": "Donna Lee", "keys": ["Ab"], "style": "Jazz Standard", "priority": 1},
  {"name": "Four", "keys": ["Eb"], "style": "Jazz Standard", "priority": 1},
  {"name": "Giant Steps", "keys": ["B"], "style": "Jazz Standard", "priority": 1},
  {"name": "Green Dolphin Street", "keys": ["C", "Eb"], "style": "Standard", "priority": 1},
  {"name": "Groovin' High", "keys": ["Eb"], "style": "Jazz Standard", "priority": 1},
  {"name": "Have You Met Miss Jones", "keys": ["F"], "style": "Standard", "priority": 1, "level": 1},
  {"name": "How High the Moon", "keys": ["G"], "style": "Standard", "priority": 1},
  {"name": "I Hear A Rhapsody", "keys": ["Eb"], "style": "Standard", "priority": 1},
  {"name": "I Love You", "keys": ["F"], "style": "Standard", "priority": 1},
  {"name": "I’ll Remember April", "keys": ["G"], "style": "Standard", "priority": 1},
  {"name": "Impressions", "keys": ["Dm"], "style": "Jazz Standard", "priority": 1},
  {"name": "Invitation", "keys": ["Cm"], "style": "Jazz Standard", "priority": 1},
  {"name": "It Could Happen To You", "keys": ["Eb"], "style": "Standard", "priority": 1},
  {"name": "Just Friends", "keys": ["G"], "style": "Standard", "priority": 1, "level": 1},
  {"name": "Lady Bird", "keys": ["C"], "style": "Jazz Standard", "priority": 1},
  {"name": "Mr PC", "keys": ["Cm"], "style": "Jazz Standard", "priority": 1, "level": 1},
  {"name": "Now’s the Time", "keys": ["F"], "style": "Blues", "priority": 1},
  {"name": "Oleo", "keys": ["Bb"], "style": "Rhythm Changes", "priority": 1},
  {"name": "Out of Nowhere", "keys": ["G"], "style": "Standard", "priority": 1},
  {"name": "Softly as in a Morning Sunrise", "keys": ["Cm"], "style": "Standard", "priority": 1, "level": 3},
  {"name": "Solar", "keys": ["Cm"], "style": "Jazz Standard", "priority": 1, "level": 1},
  {"name": "Stablemates", "keys": ["Db"], "style": "Jazz Standard", "priority": 1},
  {"name": "Stella by Starlight", "keys": ["Bb"], "style": "Standard", "priority": 1, "level": 2},
  {"name": "Straight No Chaser", "keys": ["F", "Bb"], "style": "Blues", "priority": 1},
  {"name": "Summertime", "keys": ["Am", "Dm"], "style": "Standard", "priority": 1, "level": 1},
  {"name": "Tenor Madness", "keys": ["Bb"], "style": "Blues", "priority": 1},
  {"name": "There is No Greater Love", "keys": ["Bb"], "style": "Standard", "priority": 1},
  {"name": "There Will Never Be Another You", "keys": ["Eb"], "style": "Standard", "priority": 1, "level": 2},
  {"name": "What is this Thing Called Love", "keys": ["C"], "style": "Standard", "priority": 1, "level": 1},
  {"name": "Airegin", "keys": ["Fm"], "style": "Jazz Standard", "priority": 2},
  {"name": "All of Me", "keys": ["C"], "style": "Standard", "priority": 2},
  {"name": "Alone Together", "keys": ["Dm"], "style": "Jazz Standard", "priority": 2, "level": 1},
  {"name": "Along Came Betty", "keys": ["Ab"], "style": "Jazz Standard", "priority": 2},
  {"name": "Ask Me Now", "keys": ["Db"], "style": "Jazz Standard", "priority": 2},
  {"name": "Au Privave", "keys": ["F"], "style": "Jazz Standard", "priority": 2},
  {"name": "Beatrice", "keys": ["F"], "style": "Jazz Standard", "priority": 2},
  {"name": "Blues for Alice", "keys": ["F"], "style": "Blues", "priority": 2, "level": 1},
  {"name": "Bolivia", "keys": ["D"], "style": "Jazz Standard", "priority": 2},
  {"name": "Bye Bye Blackbird", "keys": ["F"], "style": "Standard", "priority": 2},
  {"name": "C Jam Blues", "keys": ["C"], "style": "Blues", "priority": 2},
  {"name": "Caravan", "keys": ["Fm"], "style": "Jazz Standard", "priority": 2},
  {"name": "Confirmation", "keys": ["F"], "style": "Jazz Standard", "priority": 2},
  {"name": "Days of Wine and Roses", "keys": ["F"], "style": "Standard", "priority": 2, "level": 1},
  {"name": "Dolphin Dance", "keys": ["Eb"], "style": "Jazz Standard", "priority": 2},
  {"name": "Don't Get Around Much Anymore", "keys": ["C"], "style": "Standard", "priority": 2},
  {"name": "East of the Sun", "keys": ["G"], "style": "Standard", "priority": 2},
  {"name": "In a Sentimental Mood", "keys": ["Dm"], "style": "Ballad", "priority": 2},
  {"name": "In Your Own Sweet Way", "keys": ["Eb", "Bb"], "style": "Standard", "priority": 2},
  {"name": "Inner Urge", "keys": ["G"], "style": "Jazz Standard", "priority": 2},
  {"name": "Isfahan", "keys": ["Db"], "style": "Standard", "priority": 2},
  {"name": "Joy Spring", "keys": ["F"], "style": "Jazz Standard", "priority": 2},
  {"name": "Lazy Bird", "keys": ["G"], "style": "Jazz Standard", "priority": 2},
  {"name": "Like Someone in Love", "keys": ["Eb", "C"], "style": "Standard", "priority": 2, "level": 1},
  {"name": "Milestones (new)", "keys": ["Gm"], "style": "Jazz Standard", "priority": 2},
  {"name": "Minority", "keys": ["Fm"], "style": "Jazz Standard", "priority": 2},
  {"name": "Moment’s Notice", "keys": ["Eb"], "style": "Jazz Standard", "priority": 2},
  {"name": "Moonlight in Vermont", "keys": ["Eb"], "style": "Ballad", "priority": 2},
  {"name": "My One and Only Love", "keys": ["C"], "style": "Ballad", "priority": 2},
  {"name": "Nardis", "keys": ["Em"], "style": "Jazz Standard", "priority": 2},
  {"name": "Nica’s Dream", "keys": ["Bbm"], "style": "Latin", "priority": 2},
  {"name": "Night and Day", "keys": ["C"], "style": "Standard", "priority": 2},
  {"name": "One Finger Snap", "keys": ["Eb"], "style": "Jazz Standard", "priority": 2},
  {"name": "Pent-up House", "keys": ["G"], "style": "Jazz Standard", "priority": 2},
  {"name": "Recordame", "keys": ["Am"], "style": "Latin", "priority": 2},
  {"name": "Rhythm-a-Ning", "keys": ["Bb"], "style": "Rhythm Changes", "priority": 2},
  {"name": "Round Midnight", "keys": ["Ebm"], "style": "Jazz Standard", "priority": 2},
  {"name": "Scrapple from the Apple", "keys": ["F"], "style": "Jazz Standard", "priority": 2},
  {"name": "Serenity", "keys": ["Eb"], "style": "Jazz Standard", "priority": 2},
  {"name": "Seven Steps to Heaven", "keys": ["F"], "style": "Jazz Standard", "priority": 2},
  {"name": "Soul Eyes", "keys": ["Cm"], "style": "Ballad", "priority": 2, "level": 2},
  {"name": "Star Eyes", "keys": ["Eb"], "style": "Jazz Standard", "priority": 2},
  {"name": "Take the “A” Train", "keys": ["C"], "style": "Jazz Standard", "priority": 2},
  {"name": "The Song is You", "keys": ["C"], "style": "Standard", "priority": 2},
  {"name": "The Theme", "keys": ["Bb"], "style": "Rhythm Changes", "priority": 2},
  {"name": "This I Dig of You", "keys": ["Bb"], "style": "Jazz Standard", "priority": 2},
  {"name": "Tune-Up", "keys": ["D"], "style": "Jazz Standard", "priority": 2},
  {"name": "UMMG", "keys": ["Db"], "style": "Jazz Standard", "priority": 2},
  {"name": "Without a Song", "keys": ["Eb"], "style": "Standard", "priority": 2},
  {"name": "Yardbird Suite", "keys": ["C"], "style": "Jazz Standard", "priority": 2},
  {"name": "Yes or No", "style": "Jazz Standard", "priority": 2},
  {"name": "You Stepped Out of a Dream", "keys": ["C"], "style": "Standard", "priority": 2, "level": 1},
  {"name": "26-2", "keys": ["F"], "style": "Jazz Standard", "priority": 3},
  {"name": "A Night in Tunisia", "keys": ["Dm"], "style": "Jazz Standard", "priority": 3},
  {"name": "All Blues", "keys": ["G"], "style": "Jazz Standard", "priority": 3},
  {"name": "All of You", "keys": ["Eb"], "style": "Standard", "priority": 3},
  {"name": "Angel Eyes", "keys": ["Cm"], "style": "Standard", "priority": 3},
  {"name": "Autumn in New York", "keys": ["F"], "style": "Standard", "priority": 3, "level": 1},
  {"name": "Beautiful Love", "keys": ["Dm"], "style": "Standard", "priority": 3, "level": 1},
  {"name": "Bemsha Swing", "keys": ["C"], "style": "Jazz Standard", "priority": 3},
  {"name": "Black Narcissus", "keys": ["G#m"], "style": "Jazz Standard", "priority": 3, "level": 1},
  {"name": "Black Nile", "keys": ["Dm"], "style": "Jazz Standard", "priority": 3},
  {"name": "Black Orpheus", "keys": ["Am"], "style": "Latin", "priority": 3, "level": 1},
  {"name": "Blue Monk", "keys": ["Bb"], "style": "Jazz Standard", "priority": 3, "level": 2},
  {"name": "But Beautiful", "keys": ["G"], "style": "Standard", "priority": 3},
  {"name": "But Not for Me", "keys": ["Eb"], "style": "Standard", "priority": 3},
  {"name": "Ceora", "keys": ["Ab"], "style": "Latin", "priority": 3},
  {"name": "Cheryl", "keys": ["C"], "style": "Blues", "priority": 3},
  {"name": "Come Rain or Come Shine", "keys": ["F"], "style": "Standard", "priority": 3},
  {"name": "Con Alma", "keys": ["C"], "style": "Latin", "priority": 3},
  {"name": "Corcovado (Quiet Nights)", "keys": ["C"], "style": "Latin", "priority": 3},
  {"name": "Countdown", "keys": ["Bb"], "style": "Jazz Standard", "priority": 3},
  {"name": "Criss Cross", "keys": ["Gm"], "style": "Jazz Standard", "priority": 3},
  {"name": "Daahoud", "keys": ["Eb"], "style": "Jazz Standard", "priority": 3},
  {"name": "Desafinado", "keys": ["F"], "style": "Latin", "priority": 3},
  {"name": "Doxy", "keys": ["Bb"], "style": "Jazz Standard", "priority": 3},
  {"name": "Easy to Love", "keys": ["G"], "style": "Standard", "priority": 3},
  {"name": "Embraceable You", "keys": ["G"], "style": "Ballad", "priority": 3},
  {"name": "Epistrophy", "keys": ["Db"], "style": "Jazz Standard", "priority": 3},
  {"name": "Equinox", "keys": ["C#m"], "style": "Blues", "priority": 3, "level": 1},
  {"name": "ESP", "keys": ["F"], "style": "Jazz Standard", "priority": 3},
  {"name": "Everything Happens to Me", "keys": ["Bb"], "style": "Ballad", "priority": 3},
  {"name": "Evidence", "keys": ["Eb"], "style": "Jazz Standard", "priority": 3},
  {"name": "Falling Grace", "keys": ["Ab"], "style": "Jazz Standard", "priority": 3},
  {"name": "Fee-Fi-Fo-Fum", "keys": ["Bb"], "style": "Jazz Standard", "priority": 3},
  {"name": "Footprints", "keys": ["Cm"], "style": "Jazz Standard", "priority": 3},
  {"name": "For All We Know", "keys": ["Eb"], "style": "Ballad", "priority": 3},
  {"name": "Four In One", "keys": ["Eb"], "style": "Jazz Standard", "priority": 3},
  {"name": "Freddie Freeloader", "keys": ["Bb"], "style": "Jazz Standard", "priority": 3, "level": 1},
  {"name": "Freedom Jazz Dance", "keys": ["Bb"], "style": "Jazz Standard", "priority": 3},
  {"name": "Good Bait", "keys": ["Bb"], "style": "Jazz Standard", "priority": 3, "level": 1},
  {"name": "Goodbye Pork Pie Hat", "keys": ["Eb"], "style": "Ballad", "priority": 3},
  {"name": "Green Chimneys", "keys": ["G#m"], "style": "Jazz Standard", "priority": 3},
  {"name": "Half Nelson", "keys": ["C"], "style": "Jazz Standard", "priority": 3},
  {"name": "Hot House", "keys": ["C"], "style": "Jazz Standard", "priority": 3},
  {"name": "How Deep is the Ocean", "keys": ["Eb"], "style": "Standard", "priority": 3, "level": 1},
  {"name": "I Can’t Get Started", "keys": ["C"], "style": "Ballad", "priority": 3},
  {"name": "I Could Write a Book", "keys": ["C"], "style": "Standard", "priority": 3},
  {"name": "I Got Rhythm", "keys": ["Bb"], "style": "Standard", "priority": 3},
  {"name": "I Mean You", "keys": ["F"], "style": "Jazz Standard", "priority": 3},
  {"name": "I Remember Clifford", "keys": ["Eb"], "style": "Ballad", "priority": 3, "level": 1},
  {"name": "I Remember You", "keys": ["F"], "style": "Standard", "priority": 3},
  {"name": "I Should Care", "keys": ["C"], "style": "Standard", "priority": 3},
  {"name": "I Thought about You", "keys": ["F"], "style": "Ballad", "priority": 3},
  {"name": "If I Were a Bell", "keys": ["F"], "style": "Standard", "priority": 3},
  {"name": "In Walked Bud", "keys": ["Ab"], "style": "Jazz Standard", "priority": 3},
  {"name": "Indiana", "keys": ["F"], "style": "Standard", "priority": 3},
  {"name": "Infant Eyes", "keys": ["Eb"], "style": "Standard", "priority": 3},
  {"name": "Isotope", "keys": ["C"], "style": "Jazz Standard", "priority": 3},
  {"name": "If I Should Lose You", "keys": ["Bb"], "style": "Standard", "priority": 3},
  {"name": "It’s You or No One", "keys": ["F"], "style": "Standard", "priority": 3},
  {"name": "Jordu", "keys": ["Cm"], "style": "Jazz Standard", "priority": 3},
  {"name": "Just in Time", "keys": ["Bb"], "style": "Standard", "priority": 3},
  {"name": "Just One of those Things", "keys": ["F"], "style": "Standard", "priority": 3},
  {"name": "Killer Joe", "keys": ["C"], "style": "Jazz Standard", "priority": 3},
  {"name": "Laura", "keys": ["C"], "style": "Ballad", "priority": 3},
  {"name": "Let's Cool One", "keys": ["Eb"], "style": "Jazz Standard", "priority": 3},
  {"name": "Little Sunflower", "keys": ["Dm"], "style": "Jazz Standard", "priority": 3},
  {"name": "Love for Sale", "keys": ["Bbm"], "style": "Standard", "priority": 3},
  {"name": "Lullaby of Birdland", "keys": ["Ab"], "style": "Standard", "priority": 3, "level": 1},
  {"name": "Lush Life", "keys": ["Db"], "style": "Ballad", "priority": 3},
  {"name": "Maiden Voyage", "keys": ["D"], "style": "Jazz Standard", "priority": 3},
  {"name": "Milestones (Miles)", "keys": ["Bb"], "style": "Jazz Standard", "priority": 3},
  {"name": "Misty", "keys": ["Eb"], "style": "Ballad", "priority": 3, "level": 1},
  {"name": "Monk's Dream", "keys": ["C"], "style": "Jazz Standard", "priority": 3},
  {"name": "Monk's Mood", "keys": ["Db"], "style": "Jazz Standard", "priority": 3},
  {"name": "My Foolish Heart", "keys": ["Bb"], "style": "Ballad", "priority": 3, "level": 1},
  {"name": "My Funny Valentine", "keys": ["Cm"], "style": "Ballad", "priority": 3},
  {"name": "My Shining Hour", "keys": ["C"], "style": "Standard", "priority": 3},
  {"name": "My Ship", "keys": ["F"], "style": "Ballad", "priority": 3},
  {"name": "Nefertiti", "keys": ["Ab"], "style": "Jazz Standard", "priority": 3},
  {"name": "Night Dreamer", "keys": ["G"], "style": "Jazz Standard", "priority": 3},
  {"name": "Old Folks", "keys": ["F"], "style": "Ballad", "priority": 3},
  {"name": "One Note Samba", "keys": ["Bb"], "style": "Latin", "priority": 3},
  {"name": "Ornithology", "keys": ["G"], "style": "Jazz Standard", "priority": 3},
  {"name": "Peace", "keys": ["Bb"], "style": "Ballad", "priority": 3},
  {"name": "Pensativa", "keys": ["Gb"], "style": "Jazz Standard", "priority": 3},
  {"name": "Perdido", "keys": ["Bb"], "style": "Standard", "priority": 3},
  {"name": "Polkadots and Moonbeams", "keys": ["F"], "style": "Ballad", "priority": 3},
  {"name": "Prelude to a Kiss", "keys": ["C"], "style": "Ballad", "priority": 3},
  {"name": "Ruby My Dear", "keys": ["Eb"], "style": "Ballad", "priority": 3},
  {"name": "Salt Peanuts", "keys": ["Bb"], "style": "Rhythm Changes", "priority": 3},
  {"name": "Sandu", "keys": ["Eb"], "style": "Blues", "priority": 3},
  {"name": "Satin Doll", "keys": ["C"], "style": "Standard", "priority": 3},
  {"name": "Secret Love", "keys": ["Eb"], "style": "Standard", "priority": 3},
  {"name": "Skylark", "keys": ["Eb"], "style": "Ballad", "priority": 3},
  {"name": "So What", "keys": ["Dm"], "style": "Jazz Standard", "priority": 3, "level": 1},
  {"name": "Someday my Prince will Come", "keys": ["Bb"], "style": "Standard", "priority": 3, "level": 1},
  {"name": "Song For My Father", "keys": ["Fm"], "style": "Latin", "priority": 3},
  {"name": "Sonnymoon for Two", "keys": ["Bb"], "style": "Blues", "priority": 3},
  {"name": "Speak Low", "keys": ["F"], "style": "Standard", "priority": 3},
  {"name": "Speak No Evil", "keys": ["Cm"], "style": "Jazz Standard", "priority": 3},
  {"name": "St. Thomas", "keys": ["C"], "style": "Latin", "priority": 3},
  {"name": "Steeplechase", "keys": ["F"], "style": "Rhythm Changes", "priority": 3},
  {"name": "Stompin’ at the Savoy", "keys": ["Db"], "style": "Standard", "priority": 3},
  {"name": "Sweet Georgia Brown", "keys": ["Ab", "F"], "style": "Standard", "priority": 3},
  {"name": "Tenderly", "keys": ["Eb"], "style": "Standard", "priority": 3},
  {"name": "The Girl From Ipanema", "keys": ["F"], "style": "Latin", "priority": 3},
  {"name": "The Jitterbug Waltz", "keys": ["Eb"], "style": "Standard", "priority": 3},
  {"name": "The Night Has 1000 Eyes", "keys": ["G"], "style": "Standard", "priority": 3},
  {"name": "The Shadow of your Smile", "keys": ["G"], "style": "Latin", "priority": 3},
  {"name": "The Way You Look Tonight", "keys": ["F"], "style": "Standard", "priority": 3},
  {"name": "These Foolish Things", "keys": ["Eb"], "style": "Standard", "priority": 3},
  {"name": "Think of One", "keys": ["F"], "style": "Jazz Standard", "priority": 3},
  {"name": "Up Jumped Spring", "keys": ["Bb"], "style": "Standard", "priority": 3},
  {"name": "Walkin’", "keys": ["F"], "style": "Blues", "priority": 3},
  {"name": "Watermelon Man", "keys": ["F"], "style": "Funk", "priority": 3},
  {"name": "Wave", "keys": ["D"], "style": "Latin", "priority": 3},
  {"name": "Well, you Needn’t", "keys": ["F"], "style": "Jazz Standard", "priority": 3},
  {"name": "What’s New?", "keys": ["C"], "style": "Ballad", "priority": 3},
  {"name": "Whisper Not", "keys": ["Cm"], "style": "Jazz Standard", "priority": 3, "level": 1},
  {"name": "Wild Flower", "keys": ["Bb"], "style": "Ballad", "priority": 3},
  {"name": "Windows", "keys": ["Bm"], "style": "Jazz Standard", "priority": 3},
  {"name": "Witch Hunt", "keys": ["Cm"], "style": "Jazz Standard", "priority": 3},
  {"name": "Witchcraft", "keys": ["F"], "style": "Standard", "priority": 3},
  {"name": "Woody ‘n You", "keys": ["Db"], "style": "Jazz Standard", "priority": 3},
  {"name": "Yesterdays", "keys": ["Dm"], "style": "Ballad", "priority": 3},
  {"name": "You Don’t Know What Love Is", "keys": ["Fm"], "style": "Ballad", "priority": 3, "level": 3},
  {"name": "A Child is Born", "keys": ["Bb"], "style": "Standard", "priority": 4},
  {"name": "A Day in the Life of a Fool", "keys": ["Am"], "style": "Standard", "priority": 4},
  {"name": "Afternoon in Paris", "keys": ["C"], "style": "Standard", "priority": 4},
  {"name": "Ah-Leu-Cha", "keys": ["F"], "style": "Jazz Standard", "priority": 4},
  {"name": "Alice in Wonderland", "keys": ["C"], "style": "Standard", "priority": 4},
  {"name": "All God’s Chillun", "keys": ["F"], "style": "Jazz Standard", "priority": 4},
  {"name": "April in Paris", "keys": ["C"], "style": "Standard", "priority": 4},
  {"name": "Bag’s Groove", "keys": ["F"], "style": "Jazz Standard", "priority": 4},
  {"name": "Bernie's Tune", "keys": ["Dm"], "style": "Jazz Standard", "priority": 4},
  {"name": "Bessie’s Blues", "keys": ["Eb"], "style": "Blues", "priority": 4},
  {"name": "Blue in Green", "keys": ["Dm"], "style": "Jazz Standard", "priority": 4},
  {"name": "Bluesette", "keys": ["Bb"], "style": "Jazz Standard", "priority": 4},
  {"name": "Chelsea Bridge", "keys": ["Db"], "style": "Jazz Standard", "priority": 4},
  {"name": "Conception", "keys": ["Db"], "style": "Jazz Standard", "priority": 4},
  {"name": "Cousin Mary", "keys": ["Ab"], "style": "Jazz Standard", "priority": 4},
  {"name": "CTA", "keys": ["Bb"], "style": "Jazz Standard", "priority": 4},
  {"name": "Dearly Beloved", "keys": ["C"], "style": "Ballad", "priority": 4},
  {"name": "Dig", "keys": ["Ab"], "style": "Jazz Standard", "priority": 4},
  {"name": "Don't Blame Me", "keys": ["C"], "style": "Ballad", "priority": 4},
  {"name": "Easy Living", "keys": ["F"], "style": "Ballad", "priority": 4},
  {"name": "El Gaucho", "keys": ["F"], "style": "Jazz Standard", "priority": 4},
  {"name": "Emily", "keys": ["G"], "style": "Ballad", "priority": 4},
  {"name": "End of a Love Affair", "keys": ["F"], "style": "Standard", "priority": 4},
  {"name": "Georgia On My Mind", "keys": ["F"], "style": "Standard", "priority": 4},
  {"name": "Gone with the Wind", "keys": ["Eb"], "style": "Standard", "priority": 4},
  {"name": "Hackensack", "keys": ["F"], "style": "Jazz Standard", "priority": 4},
  {"name": "Here’s That Rainy Day", "keys": ["G"], "style": "Standard", "priority": 4},
  {"name": "Hi-Fly", "keys": ["C"], "style": "Jazz Standard", "priority": 4},
  {"name": "How Insensitive", "keys": ["Dm"], "style": "Latin", "priority": 4},
  {"name": "I Didn’t Know What Time it Was", "keys": ["G"], "style": "Standard", "priority": 4},
  {"name": "I Fall in Love too Easily", "keys": ["Eb"], "style": "Ballad", "priority": 4, "level": 1},
  {"name": "I Got it Bad and that ain’t Good", "keys": ["G"], "style": "Standard", "priority": 4},
  {"name": "I Want to Talk about You", "keys": ["Eb"], "style": "Ballad", "priority": 4},
  {"name": "I’ll Take Romance", "keys": ["F"], "style": "Standard", "priority": 4},
  {"name": "I’m Old Fashioned", "keys": ["F"], "style": "Ballad", "priority": 4},
  {"name": "I’ve Grown Accustomed to Her Face", "keys": ["Eb"], "style": "Ballad", "priority": 4},
  {"name": "If You Could See Me Now", "keys": ["Eb"], "style": "Ballad", "priority": 4},
  {"name": "In A Mellow Tone", "keys": ["Ab"], "style": "Standard", "priority": 4},
  {"name": "Israel", "keys": ["Dm"], "style": "Jazz Standard", "priority": 4},
  {"name": "It Don’t Mean a Thing", "keys": ["Bb"], "style": "Standard", "priority": 4},
  {"name": "It Might As Well Be Spring", "keys": ["G"], "style": "Standard", "priority": 4},
  {"name": "It’s All Right with Me", "keys": ["Cm"], "style": "Standard", "priority": 4},
  {"name": "Joshua", "keys": ["Dm"], "style": "Jazz Standard", "priority": 4},
  {"name": "Juju", "keys": ["B"], "style": "Jazz Standard", "priority": 4},
  {"name": "Lament", "keys": ["Fm"], "style": "Ballad", "priority": 4, "level": 1},
  {"name": "Lester Leaps In", "keys": ["Bb"], "style": "Rhythm Changes", "priority": 4},
  {"name": "Litha", "keys": ["D"], "style": "Jazz Standard", "priority": 4},
  {"name": "Long Ago and Far Away", "keys": ["F"], "style": "Standard", "priority": 4},
  {"name": "Love Walked In", "keys": ["Eb"], "style": "Standard", "priority": 4},
  {"name": "Lover", "keys": ["Eb"], "style": "Standard", "priority": 4},
  {"name": "Lover Come Back to Me", "keys": ["Eb"], "style": "Standard", "priority": 4},
  {"name": "Loverman", "keys": ["F"], "style": "Ballad", "priority": 4},
  {"name": "Mack the Knife", "keys": ["Bb"], "style": "Standard", "priority": 4},
  {"name": "Mahjong", "keys": ["Fm"], "style": "Jazz Standard", "priority": 4},
  {"name": "Manteca", "keys": ["Bb"], "style": "Latin", "priority": 4},
  {"name": "Meditation", "keys": ["C"], "style": "Latin", "priority": 4},
  {"name": "Misterioso", "keys": ["Bb"], "style": "Blues", "priority": 4},
  {"name": "Monk’s Mood", "keys": ["Db"], "style": "Jazz Standard", "priority": 4},
  {"name": "Mr Clean", "keys": ["Fm"], "style": "Funk", "priority": 4},
  {"name": "My Romance", "keys": ["C"], "style": "Standard", "priority": 4},
  {"name": "Naima", "keys": ["Ab"], "style": "Ballad", "priority": 4},
  {"name": "On the Sunny Side of the Street", "keys": ["C"], "style": "Standard", "priority": 4},
  {"name": "Once I Loved", "keys": ["Dm"], "style": "Latin", "priority": 4},
  {"name": "Our Delight", "keys": ["Ab"], "style": "Jazz Standard", "priority": 4},
  {"name": "Our Love is Here to Stay", "keys": ["F"], "style": "Standard", "priority": 4},
  {"name": "Over the Rainbow", "keys": ["Eb"], "style": "Standard", "priority": 4},
  {"name": "Passion Dance", "keys": ["F"], "style": "Jazz Standard", "priority": 4},
  {"name": "Satellite", "keys": ["G"], "style": "Jazz Standard", "priority": 4},
  {"name": "Smoke Gets in your Eyes", "keys": ["Eb"], "style": "Ballad", "priority": 4},
  {"name": "Some Other Blues", "keys": ["F"], "style": "Blues", "priority": 4},
  {"name": "Someone to Watch Over Me", "keys": ["Eb"], "style": "Ballad", "priority": 4},
  {"name": "Sophisticated Lady", "keys": ["Ab"], "style": "Ballad", "priority": 4},
  {"name": "Spring Can Really Hang You Up", "keys": ["C"], "style": "Ballad", "priority": 4},
  {"name": "Spring is Here", "keys": ["Ab"], "style": "Standard", "priority": 4},
  {"name": "Stardust", "keys": ["Db"], "style": "Standard", "priority": 4},
  {"name": "Sugar", "keys": ["Cm"], "style": "Blues", "priority": 4, "level": 1},
  {"name": "Tangerine", "keys": ["F"], "style": "Standard", "priority": 4},
  {"name": "The Duke", "keys": ["C"], "style": "Standard", "priority": 4},
  {"name": "Things ain’t what they used to Be", "keys": ["Db"], "style": "Blues", "priority": 4},
  {"name": "Triste", "keys": ["A"], "style": "Latin", "priority": 4},
  {"name": "Unit Seven", "keys": ["C"], "style": "Blues", "priority": 4},
  {"name": "Valse Hot", "keys": ["Ab"], "style": "Jazz Standard", "priority": 4},
  {"name": "When I Fall in Love", "keys": ["Eb"], "style": "Ballad", "priority": 4},
  {"name": "When Lights are Low", "keys": ["Eb"], "style": "Ballad", "priority": 4},
  {"name": "When Sunny Gets Blue", "keys": ["F"], "style": "Ballad", "priority": 4, "level": 1},
  {"name": "You’re a Weaver of Dreams", "keys": ["C"], "style": "Standard", "priority": 4, "level": 1},
  {"name": "Some Other Time", "keys": ["C"], "style": "Ballad", "priority": 3, "level": 0, "notes": "From spreadsheet: D+", "mine": true}
];
